# Generated by Django 5.0.1 on 2024-02-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chow', '0002_remove_product_bestseller_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='food_image',
        ),
    ]
