# Generated by Django 5.0.1 on 2024-03-31 22:10

import chow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chow', '0004_alter_product_food_image_cart_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='log',
        ),
        migrations.DeleteModel(
            name='reg',
        ),
        migrations.AlterField(
            model_name='product',
            name='food_image',
            field=models.ImageField(upload_to=chow.models.getFileName),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
