# Generated by Django 5.0.1 on 2024-03-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chow', '0005_remove_cart_product_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFoods1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150)),
                ('dish_description', models.CharField(max_length=1000)),
                ('dish_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('dish_count', models.IntegerField()),
                ('spice_or_sweet_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('healthier_low_kcal_version', models.BooleanField(choices=[('lowkcal', 'Low Calorie'), ('regular', 'The Usual')], default='regular', max_length=20)),
            ],
        ),
    ]
