# Generated by Django 5.0.1 on 2024-03-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chow', '0006_customfoods1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfoods1',
            name='spice_or_sweet_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
